version: '3.8'

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080
    volumes:
      - ./config:/etc/searxng
